import React, { Component } from 'react';
import './TutorialModalBodyOne.css';

export class TutorialModalBodyOne extends Component {
	render() {
		return (
			<div className='container-fluid'>
				<div className='row' id='first-modal-row'>
					<div className='col-12'>
						<h5>Introduction</h5>
						<p id='first-modal-sentence'>Hello there! If you are reading this and are looking for a easy to follow tutorial to help you create your new character, then you've come to the right place!</p>
						<p id='second-modal-sentence'><small>If not, then... well... uh... there's complementary free pizza in the back of the room, if you want any.</small></p><br/>
						<p>Now I know what you're thinking: 'Why would I need a tutorial when a lot of this stuff looks easy to fill in and/or I already have (a friend / an official guidebook / my imagination) to help me make my own character?' Well there are many answers I can give to that, especially to all you first-time role-players out there, but the biggest piece of advice I can give in regards to character creation is that there are times when there's a difference between characters you <span id='first-modal-emphasis'>envision playing</span> and characters you are <span id='second-modal-emphasis'>currently capable/comfortable being</span> while in-game.</p><br/>
						<p>To give you an example of what I mean, here's what happened to me the first time I ever played a table-top RPG in a medium-large sized group: While many of the others in my group created characters that focused more on the combative or magic-oriented aspects of their personas, I wanted to create a character that relied more on the charisma and persuasion abilities to complete my objectives. While I never played a table-top RPG before, I had previously played various video game RPGs that featured characters with similar skillsets and thus thought my previous experiences would carry over into this medium of role-playing.</p><br/>
						<p id='third-modal-sentence'><span>Don't make this same mistake as I did!</span> While many video game RPGs do allow the ability to approach situations in multiple ways (i.e. with persuasion or intimidation), but many of these games' scenarios are pre-scripted and, more often than not, these games perform your characters speech/actions based on simple button inputs from the player (a.k.a. You). Table-top RPGs don't have those automated responses and much of what your character(s) says or does depends largely on how <strong>YOU</strong> act/react in real-time.</p><br/>
						<p>I did not realize this at the time and, because of that, I was stuck with a character that I felt was unsuited/uncomfortable to me, especially since that was my first time playing that game and had little to no idea/experience on how these sort of games are typically played. Personally, I feel that this issue is a big reason why these types of games are less accessible to newcomers: their confusion, misconceptions and/or assumptions about how they create their first character makes things more difficult and needlessly frustrating at the same time, giving them a bad first impression of the game/genre as a whole.</p><br/>
						<p>The purpose of this tutorial is to help you avoid such a frustrating experience when playing the game, as well as help speed things along by walking you through each step of the character creation process. Since this is Dungeons and Dragons we're working with, we will be creating this character based on the front page of the official character sheet (Page 2 will be added in the near future). Thankfully, some of the values are shared based on certain attributes and modifiers, so I'll be sure to let you know which point values should be remembered for later steps in the tutorial and tell you when/where you can throw those numbers in. Please take note that these shared values will not automatically be sent to their relevant places and that they must be manually inputed by you. This was an intentional decision by me for two reasons: first is that I want to be sure you walk through each of these steps rather than automating it so that you are less likely to forget in the future, and second is that I wanted to ensure each attribute/skill value can be independantly customizable just in case your game and/or character is being played on special conditions outside of the general rules.</p><br/>
						<p>With all that said and out of the way, let's get started!!! Please press the 'Next Page' button below to proceed (Note: the 'Next Page' button will automatically save your current inputs, but pressing the 'Close' button will back you out without saving what's currently on the screen).</p>
					</div>
				</div>
			</div>
		)
	}
}