class CreatePosts < ActiveRecord::Migration[5.1]
  def change
    create_table :posts do |t|
      t.string :title
      t.string :author
      t.string :content
      t.boolean :dungeons_and_dragons
      t.string :dadcharacter_name
      t.string :dadcharacter_player
      t.string :dadcharacter_class
      t.integer :dadcharacter_level
      t.string :dadcharacter_race
      t.string :dadcharacter_alignment
      t.string :dadcharacter_deity
      t.string :dadcharacter_size
      t.integer :dadcharacter_age
      t.string :dadcharacter_gender
      t.string :dadcharacter_height
      t.string :dadcharacter_weight
      t.string :dadcharacter_eyes
      t.string :dadcharacter_hair
      t.string :dadcharacter_skin
      t.integer :dadcharacter_attr_str_base
      t.integer :dadcharacter_attr_str_mod
      t.integer :dadcharacter_attr_str_tempbase
      t.integer :dadcharacter_attr_str_tempmod
      t.integer :dadcharacter_attr_dex_base
      t.integer :dadcharacter_attr_dex_mod
      t.integer :dadcharacter_attr_dex_tempbase
      t.integer :dadcharacter_attr_dex_tempmod
      t.integer :dadcharacter_attr_con_base
      t.integer :dadcharacter_attr_con_mod
      t.integer :dadcharacter_attr_con_tempbase
      t.integer :dadcharacter_attr_con_tempmod
      t.integer :dadcharacter_attr_int_base
      t.integer :dadcharacter_attr_int_mod
      t.integer :dadcharacter_attr_int_tempbase
      t.integer :dadcharacter_attr_int_tempmod
      t.integer :dadcharacter_attr_wis_base
      t.integer :dadcharacter_attr_wis_mod
      t.integer :dadcharacter_attr_wis_tempbase
      t.integer :dadcharacter_attr_wis_tempmod
      t.integer :dadcharacter_attr_cha_base
      t.integer :dadcharacter_attr_cha_mod
      t.integer :dadcharacter_attr_cha_tempbase
      t.integer :dadcharacter_attr_cha_tempmod
      t.integer :dadcharacter_hp_max
      t.integer :dadcharacter_hp_current
      t.integer :dadcharacter_hp_nonlethaldamage
      t.integer :dadcharacter_speed
      t.integer :dadcharacter_ac_total
      t.integer :dadcharacter_ac_armorbonus
      t.integer :dadcharacter_ac_shieldbonus
      t.integer :dadcharacter_ac_dexmod
      t.integer :dadcharacter_ac_natarmor
      t.integer :dadcharacter_ac_deflectmod
      t.integer :dadcharacter_ac_miscmod
      t.integer :dadcharacter_damagereduction
      t.integer :dadcharacter_touch
      t.integer :dadcharacter_flatfooted
      t.integer :dadcharacter_initiative_total
      t.integer :dadcharacter_initiative_dexmod
      t.integer :dadcharacter_initiative_miscmod
      t.integer :dadcharacter_fortitude_total
      t.integer :dadcharacter_fortitude_base
      t.integer :dadcharacter_fortitude_abilitymod
      t.integer :dadcharacter_fortitude_magicmod
      t.integer :dadcharacter_fortitude_miscmod
      t.integer :dadcharacter_fortitude_tempmod
      t.integer :dadcharacter_reflex_total
      t.integer :dadcharacter_reflex_base
      t.integer :dadcharacter_reflex_abilitymod
      t.integer :dadcharacter_reflex_magicmod
      t.integer :dadcharacter_reflex_miscmod
      t.integer :dadcharacter_reflex_tempmod
      t.integer :dadcharacter_will_total
      t.integer :dadcharacter_will_base
      t.integer :dadcharacter_will_abilitymod
      t.integer :dadcharacter_will_magicmod
      t.integer :dadcharacter_will_miscmod
      t.integer :dadcharacter_will_tempmod
      t.string :dadcharacter_conditionalmod
      t.integer :dadcharacter_bab
      t.integer :dadcharacter_spellresistance
      t.integer :dadcharacter_grapple_total
      t.integer :dadcharacter_grapple_bab
      t.integer :dadcharacter_grapple_strmod
      t.integer :dadcharacter_grapple_sizemod
      t.integer :dadcharacter_grapple_miscmod
      t.string :dadcharacter_attackone_name
      t.integer :dadcharacter_attackone_bonus
      t.integer :dadcharacter_attackone_damage
      t.integer :dadcharacter_attackone_critical
      t.string :dadcharacter_attackone_range
      t.string :dadcharacter_attackone_type
      t.string :dadcharacter_attackone_note
      t.string :dadcharacter_attackone_ammoname
      t.integer :dadcharacter_attackone_ammocounter
      t.string :dadcharacter_attacktwo_name
      t.integer :dadcharacter_attacktwo_bonus
      t.integer :dadcharacter_attacktwo_damage
      t.integer :dadcharacter_attacktwo_critical
      t.string :dadcharacter_attacktwo_range
      t.string :dadcharacter_attacktwo_type
      t.string :dadcharacter_attacktwo_note
      t.string :dadcharacter_attacktwo_ammoname
      t.integer :dadcharacter_attacktwo_ammocounter
      t.string :dadcharacter_attackthree_name
      t.integer :dadcharacter_attackthree_bonus
      t.integer :dadcharacter_attackthree_damage
      t.integer :dadcharacter_attackthree_critical
      t.string :dadcharacter_attackthree_range
      t.string :dadcharacter_attackthree_type
      t.string :dadcharacter_attackthree_note
      t.string :dadcharacter_attackthree_ammoname
      t.integer :dadcharacter_attackthree_ammocounter
      t.string :dadcharacter_attackfour_name
      t.integer :dadcharacter_attackfour_bonus
      t.integer :dadcharacter_attackfour_damage
      t.integer :dadcharacter_attackfour_critical
      t.string :dadcharacter_attackfour_range
      t.string :dadcharacter_attackfour_type
      t.string :dadcharacter_attackfour_note
      t.string :dadcharacter_attackfour_ammoname
      t.integer :dadcharacter_attackfour_ammocounter
      t.string :dadcharacter_attackfive_name
      t.integer :dadcharacter_attackfive_bonus
      t.integer :dadcharacter_attackfive_damage
      t.integer :dadcharacter_attackfive_critical
      t.string :dadcharacter_attackfive_range
      t.string :dadcharacter_attackfive_type
      t.string :dadcharacter_attackfive_note
      t.string :dadcharacter_attackfive_ammoname
      t.integer :dadcharacter_attackfive_ammocounter
      t.integer :dadcharacter_skill_maxclassranks
      t.integer :dadcharacter_skill_maxcrossclassranks
      t.boolean :dadcharacter_skill_appraise_usable
      t.integer :dadcharacter_skill_appraise_skillmod
      t.integer :dadcharacter_skill_appraise_abilitymod
      t.integer :dadcharacter_skill_appraise_rank
      t.integer :dadcharacter_skill_appraise_miscmod
      t.boolean :dadcharacter_skill_balance_usable
      t.integer :dadcharacter_skill_balance_skillmod
      t.integer :dadcharacter_skill_balance_abilitymod
      t.integer :dadcharacter_skill_balance_rank
      t.integer :dadcharacter_skill_balance_miscmod
      t.boolean :dadcharacter_skill_bluff_usable
      t.integer :dadcharacter_skill_bluff_skillmod
      t.integer :dadcharacter_skill_bluff_abilitymod
      t.integer :dadcharacter_skill_bluff_rank
      t.integer :dadcharacter_skill_bluff_miscmod
      t.boolean :dadcharacter_skill_climb_usable
      t.integer :dadcharacter_skill_climb_skillmod
      t.integer :dadcharacter_skill_climb_abilitymod
      t.integer :dadcharacter_skill_climb_rank
      t.integer :dadcharacter_skill_climb_miscmod
      t.boolean :dadcharacter_skill_concentration_usable
      t.integer :dadcharacter_skill_concentration_skillmod
      t.integer :dadcharacter_skill_concentration_abilitymod
      t.integer :dadcharacter_skill_concentration_rank
      t.integer :dadcharacter_skill_concentration_miscmod
      t.boolean :dadcharacter_skill_craftone_usable
      t.string :dadcharacter_skill_craftone_name
      t.integer :dadcharacter_skill_craftone_skillmod
      t.integer :dadcharacter_skill_craftone_abilitymod
      t.integer :dadcharacter_skill_craftone_rank
      t.integer :dadcharacter_skill_craftone_miscmod
      t.boolean :dadcharacter_skill_crafttwo_usable
      t.string :dadcharacter_skill_crafttwo_name
      t.integer :dadcharacter_skill_crafttwo_skillmod
      t.integer :dadcharacter_skill_crafttwo_abilitymod
      t.integer :dadcharacter_skill_crafttwo_rank
      t.integer :dadcharacter_skill_crafttwo_miscmod
      t.boolean :dadcharacter_skill_craftthree_usable
      t.string :dadcharacter_skill_craftthree_name
      t.integer :dadcharacter_skill_craftthree_skillmod
      t.integer :dadcharacter_skill_craftthree_abilitymod
      t.integer :dadcharacter_skill_craftthree_rank
      t.integer :dadcharacter_skill_craftthree_miscmod
      t.boolean :dadcharacter_skill_decipherscript_usable
      t.integer :dadcharacter_skill_decipherscript_skillmod
      t.integer :dadcharacter_skill_decipherscript_abilitymod
      t.integer :dadcharacter_skill_decipherscript_rank
      t.integer :dadcharacter_skill_decipherscript_miscmod
      t.boolean :dadcharacter_skill_diplomacy_usable
      t.integer :dadcharacter_skill_diplomacy_skillmod
      t.integer :dadcharacter_skill_diplomacy_abilitymod
      t.integer :dadcharacter_skill_diplomacy_rank
      t.integer :dadcharacter_skill_diplomacy_miscmod
      t.boolean :dadcharacter_skill_disabledevice_usable
      t.integer :dadcharacter_skill_disabledevice_skillmod
      t.integer :dadcharacter_skill_disabledevice_abilitymod
      t.integer :dadcharacter_skill_disabledevice_rank
      t.integer :dadcharacter_skill_disabledevice_miscmod
      t.boolean :dadcharacter_skill_disguise_usable
      t.integer :dadcharacter_skill_disguise_skillmod
      t.integer :dadcharacter_skill_disguise_abilitymod
      t.integer :dadcharacter_skill_disguise_rank
      t.integer :dadcharacter_skill_disguise_miscmod
      t.boolean :dadcharacter_skill_escapeartist_usable
      t.integer :dadcharacter_skill_escapeartist_skillmod
      t.integer :dadcharacter_skill_escapeartist_abilitymod
      t.integer :dadcharacter_skill_escapeartist_rank
      t.integer :dadcharacter_skill_escapeartist_miscmod
      t.boolean :dadcharacter_skill_forgery_usable
      t.integer :dadcharacter_skill_forgery_skillmod
      t.integer :dadcharacter_skill_forgery_abilitymod
      t.integer :dadcharacter_skill_forgery_rank
      t.integer :dadcharacter_skill_forgery_miscmod
      t.boolean :dadcharacter_skill_gatherinfo_usable
      t.integer :dadcharacter_skill_gatherinfo_skillmod
      t.integer :dadcharacter_skill_gatherinfo_abilitymod
      t.integer :dadcharacter_skill_gatherinfo_rank
      t.integer :dadcharacter_skill_gatherinfo_miscmod
      t.boolean :dadcharacter_skill_handleanimal_usable
      t.integer :dadcharacter_skill_handleanimal_skillmod
      t.integer :dadcharacter_skill_handleanimal_abilitymod
      t.integer :dadcharacter_skill_handleanimal_rank
      t.integer :dadcharacter_skill_handleanimal_miscmod
      t.boolean :dadcharacter_skill_heal_usable
      t.integer :dadcharacter_skill_heal_skillmod
      t.integer :dadcharacter_skill_heal_abilitymod
      t.integer :dadcharacter_skill_heal_rank
      t.integer :dadcharacter_skill_heal_miscmod
      t.boolean :dadcharacter_skill_hide_usable
      t.integer :dadcharacter_skill_hide_skillmod
      t.integer :dadcharacter_skill_hide_abilitymod
      t.integer :dadcharacter_skill_hide_rank
      t.integer :dadcharacter_skill_hide_miscmod
      t.boolean :dadcharacter_skill_intimidate_usable
      t.integer :dadcharacter_skill_intimidate_skillmod
      t.integer :dadcharacter_skill_intimidate_abilitymod
      t.integer :dadcharacter_skill_intimidate_rank
      t.integer :dadcharacter_skill_intimidate_miscmod
      t.boolean :dadcharacter_skill_jump_usable
      t.integer :dadcharacter_skill_jump_skillmod
      t.integer :dadcharacter_skill_jump_abilitymod
      t.integer :dadcharacter_skill_jump_rank
      t.integer :dadcharacter_skill_jump_miscmod
      t.boolean :dadcharacter_skill_knowledgeone_usable
      t.string :dadcharacter_skill_knowledgeone_name
      t.integer :dadcharacter_skill_knowledgeone_skillmod
      t.integer :dadcharacter_skill_knowledgeone_abilitymod
      t.integer :dadcharacter_skill_knowledgeone_rank
      t.integer :dadcharacter_skill_knowledgeone_miscmod
      t.boolean :dadcharacter_skill_knowledgetwo_usable
      t.string :dadcharacter_skill_knowledgetwo_name
      t.integer :dadcharacter_skill_knowledgetwo_skillmod
      t.integer :dadcharacter_skill_knowledgetwo_abilitymod
      t.integer :dadcharacter_skill_knowledgetwo_rank
      t.integer :dadcharacter_skill_knowledgetwo_miscmod
      t.boolean :dadcharacter_skill_knowledgethree_usable
      t.string :dadcharacter_skill_knowledgethree_name
      t.integer :dadcharacter_skill_knowledgethree_skillmod
      t.integer :dadcharacter_skill_knowledgethree_abilitymod
      t.integer :dadcharacter_skill_knowledgethree_rank
      t.integer :dadcharacter_skill_knowledgethree_miscmod
      t.boolean :dadcharacter_skill_knowledgefour_usable
      t.string :dadcharacter_skill_knowledgefour_name
      t.integer :dadcharacter_skill_knowledgefour_skillmod
      t.integer :dadcharacter_skill_knowledgefour_abilitymod
      t.integer :dadcharacter_skill_knowledgefour_rank
      t.integer :dadcharacter_skill_knowledgefour_miscmod
      t.boolean :dadcharacter_skill_knowledgefive_usable
      t.string :dadcharacter_skill_knowledgefive_name
      t.integer :dadcharacter_skill_knowledgefive_skillmod
      t.integer :dadcharacter_skill_knowledgefive_abilitymod
      t.integer :dadcharacter_skill_knowledgefive_rank
      t.integer :dadcharacter_skill_knowledgefive_miscmod
      t.boolean :dadcharacter_skill_listen_usable
      t.integer :dadcharacter_skill_listen_skillmod
      t.integer :dadcharacter_skill_listen_abilitymod
      t.integer :dadcharacter_skill_listen_rank
      t.integer :dadcharacter_skill_listen_miscmod
      t.boolean :dadcharacter_skill_movesilent_usable
      t.integer :dadcharacter_skill_movesilent_skillmod
      t.integer :dadcharacter_skill_movesilent_abilitymod
      t.integer :dadcharacter_skill_movesilent_rank
      t.integer :dadcharacter_skill_movesilent_miscmod
      t.boolean :dadcharacter_skill_openlock_usable
      t.integer :dadcharacter_skill_openlock_skillmod
      t.integer :dadcharacter_skill_openlock_abilitymod
      t.integer :dadcharacter_skill_openlock_rank
      t.integer :dadcharacter_skill_openlock_miscmod
      t.boolean :dadcharacter_skill_performone_usable
      t.string :dadcharacter_skill_performone_name
      t.integer :dadcharacter_skill_performone_skillmod
      t.integer :dadcharacter_skill_performone_abilitymod
      t.integer :dadcharacter_skill_performone_rank
      t.integer :dadcharacter_skill_performone_miscmod
      t.boolean :dadcharacter_skill_performtwo_usable
      t.string :dadcharacter_skill_performtwo_name
      t.integer :dadcharacter_skill_performtwo_skillmod
      t.integer :dadcharacter_skill_performtwo_abilitymod
      t.integer :dadcharacter_skill_performtwo_rank
      t.integer :dadcharacter_skill_performtwo_miscmod
      t.boolean :dadcharacter_skill_performthree_usable
      t.string :dadcharacter_skill_performthree_name
      t.integer :dadcharacter_skill_performthree_skillmod
      t.integer :dadcharacter_skill_performthree_abilitymod
      t.integer :dadcharacter_skill_performthree_rank
      t.integer :dadcharacter_skill_performthree_miscmod
      t.boolean :dadcharacter_skill_professionone_usable
      t.string :dadcharacter_skill_professionone_name
      t.integer :dadcharacter_skill_professionone_skillmod
      t.integer :dadcharacter_skill_professionone_abilitymod
      t.integer :dadcharacter_skill_professionone_rank
      t.integer :dadcharacter_skill_professionone_miscmod
      t.boolean :dadcharacter_skill_professiontwo_usable
      t.string :dadcharacter_skill_professiontwo_name
      t.integer :dadcharacter_skill_professiontwo_skillmod
      t.integer :dadcharacter_skill_professiontwo_abilitymod
      t.integer :dadcharacter_skill_professiontwo_rank
      t.integer :dadcharacter_skill_professiontwo_miscmod
      t.boolean :dadcharacter_skill_ride_usable
      t.integer :dadcharacter_skill_ride_skillmod
      t.integer :dadcharacter_skill_ride_abilitymod
      t.integer :dadcharacter_skill_ride_rank
      t.integer :dadcharacter_skill_ride_miscmod
      t.boolean :dadcharacter_skill_search_usable
      t.integer :dadcharacter_skill_search_skillmod
      t.integer :dadcharacter_skill_search_abilitymod
      t.integer :dadcharacter_skill_search_rank
      t.integer :dadcharacter_skill_search_miscmod
      t.boolean :dadcharacter_skill_sensemotive_usable
      t.integer :dadcharacter_skill_sensemotive_skillmod
      t.integer :dadcharacter_skill_sensemotive_abilitymod
      t.integer :dadcharacter_skill_sensemotive_rank
      t.integer :dadcharacter_skill_sensemotive_miscmod
      t.boolean :dadcharacter_skill_sleightofhand_usable
      t.integer :dadcharacter_skill_sleightofhand_skillmod
      t.integer :dadcharacter_skill_sleightofhand_abilitymod
      t.integer :dadcharacter_skill_sleightofhand_rank
      t.integer :dadcharacter_skill_sleightofhand_miscmod
      t.boolean :dadcharacter_skill_spellcraft_usable
      t.integer :dadcharacter_skill_spellcraft_skillmod
      t.integer :dadcharacter_skill_spellcraft_abilitymod
      t.integer :dadcharacter_skill_spellcraft_rank
      t.integer :dadcharacter_skill_spellcraft_miscmod
      t.boolean :dadcharacter_skill_spot_usable
      t.integer :dadcharacter_skill_spot_skillmod
      t.integer :dadcharacter_skill_spot_abilitymod
      t.integer :dadcharacter_skill_spot_rank
      t.integer :dadcharacter_skill_spot_miscmod
      t.boolean :dadcharacter_skill_survival_usable
      t.integer :dadcharacter_skill_survival_skillmod
      t.integer :dadcharacter_skill_survival_abilitymod
      t.integer :dadcharacter_skill_survival_rank
      t.integer :dadcharacter_skill_survival_miscmod
      t.boolean :dadcharacter_skill_swim_usable
      t.integer :dadcharacter_skill_swim_skillmod
      t.integer :dadcharacter_skill_swim_abilitymod
      t.integer :dadcharacter_skill_swim_rank
      t.integer :dadcharacter_skill_swim_miscmod
      t.boolean :dadcharacter_skill_tumble_usable
      t.integer :dadcharacter_skill_tumble_skillmod
      t.integer :dadcharacter_skill_tumble_abilitymod
      t.integer :dadcharacter_skill_tumble_rank
      t.integer :dadcharacter_skill_tumble_miscmod
      t.boolean :dadcharacter_skill_usemagicdevice_usable
      t.integer :dadcharacter_skill_usemagicdevice_skillmod
      t.integer :dadcharacter_skill_usemagicdevice_abilitymod
      t.integer :dadcharacter_skill_usemagicdevice_rank
      t.integer :dadcharacter_skill_usemagicdevice_miscmod
      t.boolean :dadcharacter_skill_userope_usable
      t.integer :dadcharacter_skill_userope_skillmod
      t.integer :dadcharacter_skill_userope_abilitymod
      t.integer :dadcharacter_skill_userope_rank
      t.integer :dadcharacter_skill_userope_miscmod
      t.boolean :dadcharacter_skill_extraskillone_usable
      t.string :dadcharacter_skill_extraskillone_name
      t.string :dadcharacter_skill_extraskillone_keyability
      t.integer :dadcharacter_skill_extraskillone_skillmod
      t.integer :dadcharacter_skill_extraskillone_abilitymod
      t.integer :dadcharacter_skill_extraskillone_rank
      t.integer :dadcharacter_skill_extraskillone_miscmod
      t.boolean :dadcharacter_skill_extraskilltwo_usable
      t.string :dadcharacter_skill_extraskilltwo_name
      t.string :dadcharacter_skill_extraskilltwo_keyability
      t.integer :dadcharacter_skill_extraskilltwo_skillmod
      t.integer :dadcharacter_skill_extraskilltwo_abilitymod
      t.integer :dadcharacter_skill_extraskilltwo_rank
      t.integer :dadcharacter_skill_extraskilltwo_miscmod
      t.boolean :dadcharacter_skill_extraskillthree_usable
      t.string :dadcharacter_skill_extraskillthree_name
      t.string :dadcharacter_skill_extraskillthree_keyability
      t.integer :dadcharacter_skill_extraskillthree_skillmod
      t.integer :dadcharacter_skill_extraskillthree_abilitymod
      t.integer :dadcharacter_skill_extraskillthree_rank
      t.integer :dadcharacter_skill_extraskillthree_miscmod

      t.timestamps
    end
  end
end
